### ISSUE TITLE
tooltips are not legible in "Classic" Colorscheme

### ISSUE THREAD

**Issue by crowell** [Vector35/binaryninja-api#201]
![image](http://i.imgur.com/yhuwSEQ.png)

im using kubuntu's default "breeze" colorscheme, and the "classic" colorscheme in binary ninja. can't read any of the tooltip texts.

**Comment by psifertex** [comment]
Any chance you didn't restart after changing the theme? 

Changing without restarting causes a few bugs, we should probably just prompt the user afterward. 

It's also possible the theme has some bugs, will check it out when back on a computer.

**Comment by crowell** [comment]
i definitely did restart after changing themes.

**Comment by psifertex** [comment]
I reproduced it with a default Kubuntu configuration on the classic scheme, but only for the tooltips in the sidebar. Tooltips in the main window look fine. Is that the same thing you're experiencing?

**Comment by psifertex** [comment]
As an aside, kubuntu has some other oddities like single-clicking a string reference in the string view acts the same as a double click normally does, making it harder to search. Might have to investigate how to override whatever changes KDE is making.

**Comment by crowell** [comment]
@psifertex yes, that's the same as what i'm experiencing. 

 KDE's default for the file manager is single click takes you into the folder.

binaryninja is using this single vs. double click. the option in the kde settings is 

`System Settings->Input Devices->Mouse->Icons` set to double

or in `~/.config/kdeglobals` set

```ini
[KDE]
SingleClick=false
```

http://lists.qt-project.org/pipermail/interest/2012-December/005191.html gives a suggestion. 
I'll leave it as an exercise for the reader to figure out what to do with that option ;)

**Comment by psifertex** [comment]
The single click bug is fixed in dev, will be out in the next beta. 

So playing with things more, I changed the default color scheme in KDE and then changed it back and suddenly it's working for me without any changes in binary ninja. Can you try re-applying the color scheme? Also, I fiddled with the "Apply colors to non-KDE4 applications" option under `System Settings/Colors/Options` though it's currently back in the default checked state as well. 

When I install the breeze color scheme, the tooltips correctly show up in the breeze colors, for example. 
![screen shot 2016-03-24 at 1 39 34 am](https://cloud.githubusercontent.com/assets/140215/14009351/548b90a0-f161-11e5-84bd-74cf42941d53.png)
![screen shot 2016-03-24 at 1 39 47 am](https://cloud.githubusercontent.com/assets/140215/14009352/548d13ee-f161-11e5-86a3-2ceed3e20a85.png)
![screen shot 2016-03-24 at 1 38 30 am](https://cloud.githubusercontent.com/assets/140215/14009338/273d3d88-f161-11e5-9ce9-d1b22afef715.png)

**Comment by psifertex** [comment]
*ping* Can you reproduce it still? Per my comment above, it seems to be fixed for me after trying different color schemes and switching back. Also, the latest beta should have the single click bug fixed as well. 

As an aside, the classic theme in particular tries to use native colors/widgets where possible, so it's the most likely to be problematic.

**Comment by crowell** [comment]
the single click/double click is fixed for me :+1: 

The tooltips are still not readable under the classic colorscheme. I switched between each of them and then tried again on classic (all within the same session).  Only classic is illegible.

**Comment by crowell** [comment]
also, i dont have an option for "apply options to non-kde4 applications" I have "apply colors to non-qt applications" which is selected by default. I tried switching to breeze dark, then back to breeze, and it's still broken.

**Comment by psifertex** [comment]
Sorry for not closing this previously, but a QT update fixed this some time ago, breeze and classic work out of the box on Kubuntu 18.10. and have for some time iirc.
